container_path: /home/judah/corpus/run04
source_language: en
target_language: es
sources:
    - name: kde4
      source_file_path: /home/judah/corpus/kde4/kde4.es-en.en
      target_file_path: /home/judah/corpus/kde4/kde4.es-en.es
      percent_train: 100
      percent_test: 0
      percent_tune: 0
    - name: europarl
      source_file_path: /home/judah/corpus/europarl/europarl-v7.es-en.en
      target_file_path: /home/judah/corpus/europarl/europarl-v7.es-en.es
      percent_train: 100
      percent_test: 0
      percent_tune: 0
    - name: dict
      source_file_path: /home/judah/corpus/dict/dict.en-es.en
      target_file_path: /home/judah/corpus/dict/dict.en-es.es
      percent_train: 100
      percent_test: 0
      percent_tune: 0
    - name:  mongo-docs
      source_file_path: /home/judah/corpus/mongo-docs/mongo-docs.es-en.en
      target_file_path: /home/judah/corpus/mongo-docs/mongo-docs.es-en.es
      percent_train: 50
      percent_test: 20
      percent_tune: 30
source_contributions:
    train:
        - name: kde4
          percent_of_corpus: 30
        - name: europarl
          percent_of_corpus: 30
        - name: dict
          percent_of_corpus: 5
        - name: mongo-docs
          percent_of_corpus: 35
    test:
        - name: mongo-docs
          percent_of_corpus: 100
    tune:
        - name: mongo-docs
          percent_of_corpus: 100
